### ISSUE TITLE
Possible collaboration from UPES Dehradun

### ISSUE THREAD

**Issue by ChlorinePentoxide** [openAOD/Central#13]
## openAOD has received an invitation from OPEN Organization, UPES Dehradun

![image](https://user-images.githubusercontent.com/69286505/197168297-190ac7ea-527f-4b92-a7b1-aa72706b6299.png)

@aryashah2k @Daksh777 @cyberbuddy-manas what are your thoughts on this? Shall we go ahead with the participation?

**Comment by aryashah2k** [comment]
@ChlorinePentoxide I'll be more than happy to have openAOD be a part of students at UPES open source journey!

This is an exciting collaboration and I'm happy to go ahead with it buddy

Let me know what would be required as formalities if any from my side : )

**Comment by cyberbuddy-manas** [comment]
Go ahead bro, we are here to cover your back. If you need any help then
just ping me 🔥

**Comment by ChlorinePentoxide** [comment]
@aryashah2k We would probably need a logo, it is pretty much a requirement.

**Comment by aryashah2k** [comment]
> @aryashah2k We would probably need a logo, it is pretty much a requirement.

Yeah buddy, it has been a long listed requirement, I'll get something up to working on that

Meanwhile if anyone knows someone or has had past experience with designing do pitch in to create a wonderful logo for the org!

@cyberbuddy-manas @Daksh777

**Comment by ChlorinePentoxide** [comment]
![image](https://user-images.githubusercontent.com/69286505/197315347-ff77b400-9d86-450c-9104-dd909651b5af.png)
@aryashah2k @cyberbuddy-manas Shall we go ahead with the current proposal? Also we do not have swag/goodies at this point.

**Comment by aryashah2k** [comment]
> ![image](https://user-images.githubusercontent.com/69286505/197315347-ff77b400-9d86-450c-9104-dd909651b5af.png)
> @aryashah2k @cyberbuddy-manas Shall we go ahead with the current proposal? Also we do not have swag/goodies at this point.

Regarding swags and goodies, we can follow the Major League Hacking's model of providing a pack of stickers and a letter of appreciation/recommendation for the open source contributions done in our organization.

**Comment by ChlorinePentoxide** [comment]
@aryashah2k Yeah that will suffice for now, I think. Also the person in question (Asutosh Kapoor) is already a member of openAOD GitHub community, shall I ping him here, so we can move things a bit faster?

**Comment by cyberbuddy-manas** [comment]
Yeah I agree with Arya, that we can send proposal mails to the companies
like devfolio, mlh and there are many more who are willing to sponsor.

**Comment by aryashah2k** [comment]
> @aryashah2k Yeah that will suffice for now, I think. Also the person in question (Asutosh Kapoor) is already a member of openAOD GitHub community, shall I ping him here, so we can move things a bit faster?

Indeed, that would be great!

**Comment by ChlorinePentoxide** [comment]
@Kapoor-0905 We would like to switch our communication from email to GitHub issues, so that our community can react to it as well, hope you do not mind the change.
We would love to accept the collaboration offer. This is beneficial for all the members of both communities. We would also like to hear further details regarding the events. 
On our side, we will announce this collaboration in blog post on our website and announce it in our Discord group as well.

Regards,
Chlorine Pentoxide

**Comment by Kapoor-0905** [comment]
Sure we can switch our communication channel.
I have sent you the promotion and sponsorship part through my personal email: ***@***.***

Regards

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ChlorinePentoxide** [comment]
@Kapoor-0905 
We would like to move forward with collaboration.
Like I mentioned in the earlier, we are going to announce the collaboration and interested members can join your events right away. And as @aryashah2k mentioned earlier as well we will be adopting Major League Hacking model for providing goodies and a letter of recommendation. 

Regards

**Comment by ChlorinePentoxide** [comment]
@Kapoor-0905 
Our main website (https://openaod.org) has been updated to include the announcement of this collaboration. Please do let me know about the next events so we can update the website and let our community know accordingly.
Cheers

Regards,
ChlorinePentoxide

**Comment by Kapoor-0905** [comment]
> @Kapoor-0905 Our main website (https://openaod.org) has been updated to include the announcement of this collaboration. Please do let me know about the next events so we can update the website and let our community know accordingly. Cheers
> 
> Regards, ChlorinePentoxide

It looks good 👍🏻 
I request you to prepare a MoU and share it with me. 
we will be glad to collaborate with you.

Regards
Ashutosh Kapoor
External Collaboration Lead

**Comment by Daksh777** [comment]
Hey @aryashah2k, really sorry for the late reply.
The collaboration sounds awesome, I'll think of some good logo for the org in the meanwhile.

Also happy diwali to all of you!

**Comment by ChlorinePentoxide** [comment]
@aryashah2k 
The MoU has been prepared and please find it attached.
[openAOD x Open Community Memorandum of Understanding.docx](https://github.com/openAOD/Central/files/9857160/openAOD.x.Open.Community.Memorandum.of.Understanding.docx)
@Kapoor-0905 Please review the agreement. I have not mentioned the name of the authorized signatory from Open Community. Please let me know whom to mention, I will go ahead and modify the document accordingly.

Regards,
Chlorine Pentoxide

**Comment by Kapoor-0905** [comment]
Hello
The president of OPEN Community has one question that how your members will get and give benefit as we already have 300+ members in OPEN Community.

Regards
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ChlorinePentoxide** [comment]
@Kapoor-0905 Our members will benefit by having an opportunity to participate in your events and receiving a letter of recommendation from us. If you would like to propose any alternative solution please do go ahead, since we are still a small community.

**Comment by ChlorinePentoxide** [comment]
@Kapoor-0905 We have had no updates since about a week, please do inform us if there is any change and anything we could do about it.

**Comment by ChlorinePentoxide** [comment]
@Kapoor-0905 We are going to close this issue. Please let us know if you would like to proceed with this in the future.
