### ISSUE TITLE
Website rendering issue

### ISSUE THREAD

**Issue by ChlorinePentoxide** [openAOD/Central#3]
I am not sure what I can make of this but there is a icons issue I guess
![image](https://user-images.githubusercontent.com/69286505/146772340-e6fc4a98-1732-4d57-8752-125b23f8e7fa.png)
![image](https://user-images.githubusercontent.com/69286505/146772808-8acf88d4-c29c-4cb7-b7d0-7cda46d05423.png)

**Comment by Daksh777** [comment]
I'm getting a 308 error on the `icon.woff` file and I think this is a problem related to Vercel
![image](https://user-images.githubusercontent.com/43648146/146775402-0fe261eb-44cf-43e3-a675-4628e760e044.png)

Also, the CSS is also not rendering correctly after fixing the icons using my own CDN
![image](https://user-images.githubusercontent.com/43648146/146775651-726ab88a-55d7-4209-87c4-1e2a1543b607.png)

This seems to be an issue with Vercel itself.

**Comment by Daksh777** [comment]
Update: Even after using my own CDN for all the CSS files, it seems like the rendering issue is still there.
Could you try checking if Vercel could be causing this issue?

Update 2: Loading `icons.css` to my local server does not render the icons even though the icon files' CDN link is correct.

**Comment by ChlorinePentoxide** [comment]
Yes, it was a Vercel issue and kind of my fault as well. In case you are interested I set the patternhouse.tk as primary and redirected www.patternhouse.tk to it which had to be in reverse. Whenever a resource access www subdomain it would give a Error 308 Moved Permanently code. It is now fixed. But the images of companies still is not resolved.

**Comment by Daksh777** [comment]
That makes sense.

I learned a new thing today, the order of CSS is actually what was causing the issue. It should be fixed now.
