### ISSUE TITLE
Formatting 'Thanks to' section of the website

### ISSUE THREAD

**Issue by ChlorinePentoxide** [openAOD/Central#9]
* Instead of numbers in the website, possibly add the logos of the respective tech. Also add Semaphore CI/CD(https://semaphoreci.com) to the list. The logos are already in the assets directory.
* Add contributors section to the page. Recognise GitHub profiles who have at least 5 commits in the past 28 days as contributors @aryashah2k Will this condition will suit the purpose, since a lot many organisation members have not contributed to the project (yet).

**Comment by aryashah2k** [comment]
True, a contributions page will be a great addition and the criteria set is proper too! The condition could be modified as participants with atleast two merged PRs to be featured in the page.

**Comment by Daksh777** [comment]
Sounds good. I'll add a section for that.

**Comment by Daksh777** [comment]
@aryashah2k @ChlorinePentoxide are you aware of any tools which will list contributors by commits on an entire organization? I just need the names so I can put them order wise.

**Comment by aryashah2k** [comment]
> @aryashah2k @ChlorinePentoxide are you aware of any tools which will list contributors by commits on an entire organization? I just need the names so I can put them order wise.

Not aware of many, but a previous org where I used to contribute used this: https://github.com/all-contributors/all-contributors
Give me some time or wait for @ChlorinePentoxide in case he might have something to add.

**Comment by ChlorinePentoxide** [comment]
The people section of the organization will list every single member. 
And I think if you go to the Insights tab of a particular repo it will give you a statistic of lines of code committed by a member.
Of course, this is not a permanent solution i.e. it needs to updated manually after a period of time. I will let you know if a find an API to auto fetch contributions.

**Comment by ChlorinePentoxide** [comment]
@aryashah2k AllContributors is a powerful API but if we are to go down that route maybe it's best to implement in the Dev portal. I am not too sure on this but if @Daksh777 is willing to implement then why not? Sure

**Comment by aryashah2k** [comment]
> @aryashah2k AllContributors is a powerful API but if we are to go down that route maybe it's best to implement in the Dev portal. I am not too sure on this but if @Daksh777 is willing to implement then why not? Sure

Indeed, if @Daksh777 is willing, we can go ahead with it. i suggest he spends some time understanding the API and get back to us here with his idea of implementation! Otherwise even the route of utilizing statistics from the peoples section can be implemented. Only thing is he should be comfortable implementing either of the two. :)

**Comment by Daksh777** [comment]
I just checked AllContributors and they, unfortunately, do not have an API but a GitHub bot. And even if they did have an API, it only fetches the contributors on a per-repository basis so putting the contributors sorted from most to least commits won't work (which is also the same case with GitHub's stats/API).

**Comment by ChlorinePentoxide** [comment]
@cyberbuddy-manas Do you have any ideas regarding this implementation? All suggestions are appreciated.

**Comment by cyberbuddy-manas** [comment]
@ChlorinePentoxide I'll give it some thought and let you know. As of now I don't know of any tool which may help us. @PatternHouse/team-central has anyone got good experience with GitHub API ?

**Comment by cyberbuddy-manas** [comment]
> Sounds good. I'll add a section for that.

Is the section to be added in a md file or the website?

**Comment by Daksh777** [comment]
I was thinking of directly adding it to the website but I just wanted a list of members sorted by their number of commits in this organization (as opposed to a repo).
However, there doesn't seem to be any tool for that so I'll just do it manually.

**Comment by Daksh777** [comment]
Update: I found a CLI tool that lists contributors by commit: https://github.com/DAVFoundation/organization-contributors
Here's an example output with top 20 contributors:
```
Found 11 public repos.
Getting contributors for C-PatternHouse
Getting contributors for CPlusPlus-PatternHouse
Getting contributors for CSharp-PatternHouse
Getting contributors for Central
Getting contributors for Java-PatternHouse
Getting contributors for JavaScript-PatternHouse
Getting contributors for Join_PatternHouse
Getting contributors for Python-PatternHouse
Getting contributors for cli
Getting contributors for codeload
Getting contributors for guidelines
Getting information for 20 contributors.
[
  {
    user: 'aryashah2k',
    name: 'Arya Shah',
    avatar: 'https://avatars.githubusercontent.com/u/73865728?v=4',
    bio: 'Computer Science Junior with Honors in Business Systems | Software Development Engineering | Machine Learning | ',
    id: '73865728',
    contrib_count: 1395,
    repos: [
      'C-PatternHouse',
      'CPlusPlus-PatternHouse',
      'CSharp-PatternHouse',
      'Central',
      'Java-PatternHouse',
      'JavaScript-PatternHouse',
      'Join_PatternHouse',
      'Python-PatternHouse',
      'guidelines'
    ]
  },
  {
    user: 'anshyyy',
    name: 'Anshuman Sharma',
    avatar: 'https://avatars.githubusercontent.com/u/73778637?v=4',
    bio: 'Coder | Developer',
    id: '73778637',
    contrib_count: 128,
    repos: [ 'CPlusPlus-PatternHouse', 'Python-PatternHouse' ]
  },
  {
    user: 'Mahak008',
    name: null,
    avatar: 'https://avatars.githubusercontent.com/u/88129955?v=4',
    bio: null,
    id: '88129955',
    contrib_count: 127,
    repos: [ 'CPlusPlus-PatternHouse', 'Java-PatternHouse' ]
  },
  {
    user: 'kashyap1905',
    name: 'BOBBY KUMAR',
    avatar: 'https://avatars.githubusercontent.com/u/87887741?v=4',
    bio: 'Student at Maharaja Surajmal Institute of Technology (2020 - 2024) - B. Tech. - Computer Science Engineering',
    id: '87887741',
    contrib_count: 68,
    repos: [ 'C-PatternHouse', 'CPlusPlus-PatternHouse', 'Java-PatternHouse' ]
  },
  {
    user: 'ChlorinePentoxide',
    name: 'Chlorine Pentoxide',
    avatar: 'https://avatars.githubusercontent.com/u/69286505?v=4',
    bio: null,
    id: '69286505',
    contrib_count: 63,
    repos: [
      'Central',
      'Java-PatternHouse',
      'Join_PatternHouse',
      'Python-PatternHouse',
      'cli',
      'codeload',
      'guidelines'
    ]
  },
  {
    user: 'Yashesvinee',
    name: 'Yashesvinee V',
    avatar: 'https://avatars.githubusercontent.com/u/76458668?v=4',
    bio: null,
    id: '76458668',
    contrib_count: 46,
    repos: [ 'Java-PatternHouse', 'Python-PatternHouse' ]
  },
  {
    user: 'Srishti-Ahuja',
    name: 'Srishti Ahuja',
    avatar: 'https://avatars.githubusercontent.com/u/57188326?v=4',
    bio: "Django Developer | Data Science and Machine Learning Enthusiast | BTech CSE Student at Bharati Vidyapeeth's College of Engineering",
    id: '57188326',
    contrib_count: 39,
    repos: [ 'CPlusPlus-PatternHouse' ]
  },
  {
    user: 'ABHIGYANSINGH77',
    name: null,
    avatar: 'https://avatars.githubusercontent.com/u/92666396?v=4',
    bio: null,
    id: '92666396',
    contrib_count: 36,
    repos: [ 'CPlusPlus-PatternHouse' ]
  },
  {
    user: 'Abhirv08',
    name: 'Abhishek Kumar',
    avatar: 'https://avatars.githubusercontent.com/u/81900610?v=4',
    bio: 'A web developer who loves to contribute in open source.',
    id: '81900610',
    contrib_count: 27,
    repos: [ 'CPlusPlus-PatternHouse', 'Java-PatternHouse' ]
  },
  {
    user: 'phmaintainer',
    name: 'PatternHouse Maintenance and Deployment Bot',
    avatar: 'https://avatars.githubusercontent.com/u/81895890?v=4',
    bio: null,
    id: '81895890',
    contrib_count: 25,
    repos: [ 'codeload', 'guidelines' ]
  },
  {
    user: 'Punit-Choudhary',
    name: 'Punit Choudhary',
    avatar: 'https://avatars.githubusercontent.com/u/65050160?v=4',
    bio: 'I am just a GEEK \\(o_x)/',
    id: '65050160',
    contrib_count: 23,
    repos: [ 'Python-PatternHouse', 'guidelines' ]
  },
  {
    user: 'Daksh777',
    name: 'Daksh P. Jain',
    avatar: 'https://avatars.githubusercontent.com/u/43648146?v=4',
    bio: 'Programmer & Photographer',
    id: '43648146',
    contrib_count: 17,
    repos: [ 'Central', 'Python-PatternHouse' ]
  },
  {
    user: 'Sumandeep-Kaur',
    name: 'Sumandeep Kaur',
    avatar: 'https://avatars.githubusercontent.com/u/77191007?v=4',
    bio: 'CSE Undergrad | Frontend Developer | DSA Enthusiast',
    id: '77191007',
    contrib_count: 17,
    repos: [ 'C-PatternHouse', 'CPlusPlus-PatternHouse' ]
  },
  {
    user: 'Arkaprava-Nath',
    name: 'Arkaprava Nath',
    avatar: 'https://avatars.githubusercontent.com/u/90464107?v=4',
    bio: null,
    id: '90464107',
    contrib_count: 17,
    repos: [ 'C-PatternHouse', 'CPlusPlus-PatternHouse' ]
  },
  {
    user: 'Kajal13081',
    name: 'Kajal Kumari',
    avatar: 'https://avatars.githubusercontent.com/u/80222700?v=4',
    bio: null,
    id: '80222700',
    contrib_count: 14,
    repos: [ 'Java-PatternHouse' ]
  },
  {
    user: 'aakash232',
    name: 'Aakash Tyagi',
    avatar: 'https://avatars.githubusercontent.com/u/67885496?v=4',
    bio: "Junior |  Android Developer | SWoC '21\r\n" +
      'Leading with an aim to design, create & produce ideas we all are proud of! 💖',
    id: '67885496',
    contrib_count: 12,
    repos: [ 'CPlusPlus-PatternHouse', 'Java-PatternHouse' ]
  },
  {
    user: 'tamalbag117',
    name: 'TAMAL BAG',
    avatar: 'https://avatars.githubusercontent.com/u/87414354?v=4',
    bio: ' B.Tech in Computer Science and Engineering at Academy of Technology',
    id: '87414354',
    contrib_count: 12,
    repos: [ 'Java-PatternHouse' ]
  },
  {
    user: 'lovishprabhakar02',
    name: 'Lovish Prabhakar',
    avatar: 'https://avatars.githubusercontent.com/u/89595539?v=4',
    bio: 'Student, currently pursuing B.Tech(CSE) at Guru Nanak Dev University, Amritsar.',
    id: '89595539',
    contrib_count: 12,
    repos: [ 'Python-PatternHouse' ]
  },
  {
    user: 'psahithireddy',
    name: 'P.Sahithi Reddy',
    avatar: 'https://avatars.githubusercontent.com/u/62285383?v=4',
    bio: null,
    id: '62285383',
    contrib_count: 11,
    repos: [ 'CPlusPlus-PatternHouse' ]
  },
  {
    user: 'sohilkhanduja',
    name: 'Sohil Khanduja',
    avatar: 'https://avatars.githubusercontent.com/u/77602316?v=4',
    bio: 'Budding Software  developer',
    id: '77602316',
    contrib_count: 11,
    repos: [ 'Python-PatternHouse' ]
  }
]

organization-contributors v0.1.0 - Command line tool for extracting the list of contributors across an entire GitHub organization
```

Would you like me to manually start with the work?

**Comment by aryashah2k** [comment]
Yes from my side, you can start work in full force once we get a nod from @ChlorinePentoxide too in case there's something to be added or considered

**Comment by ChlorinePentoxide** [comment]
Since it is a CLI tool, I can provision a scheduled workflow on Semaphore CI/CD pipelines to automatically update a JSON file that will update every 1h (?). If getting data from a JSON file won't be an issue then the whole manual part can be skipped. @cyberbuddy-manas can also help here. Shall I go ahead with the workflow implementation if JSON parsing is not a problem @Daksh777 ?
However I see that the only measurable statistic for comparison is number of commits, will that be OK @aryashah2k ?

**Comment by Daksh777** [comment]
I think it would be very nice to use the JSON file, however, I'm not quite sure how to use it. Could you help me out with it @cyberbuddy-manas?

**Comment by cyberbuddy-manas** [comment]
@Daksh777 Yeah, I can use them well. I'll need to know more details about it though.

**Comment by cyberbuddy-manas** [comment]
> Since it is a CLI tool, I can provision a scheduled workflow on Semaphore CI/CD pipelines to automatically update a JSON file that will update every 1h (?). If getting data from a JSON file won't be an issue then the whole manual part can be skipped. @cyberbuddy-manas can also help here. Shall I go ahead with the workflow implementation if JSON parsing is not a problem @Daksh777 ? However I see that the only measurable statistic for comparison is number of commits, will that be OK @aryashah2k ?

Is this dynamic? Like does this api update data automatically?

**Comment by ChlorinePentoxide** [comment]
@cyberbuddy-manas Yes. The file gets auto-updated. I believe you could use React or MDX for that or even vanilla JS. You will need to make sure that nothing is hard-linked to any specific detail.

**Comment by cyberbuddy-manas** [comment]
@ChlorinePentoxide Definitely it's very easy to use this. Just share me the link of the webpage you want to make this table at. I'll share a design in which I'll be making a format to present their images, names, contributions and whatever data is available.

**Comment by ChlorinePentoxide** [comment]
Name the file 'contributors.html' in the Sources/WebMain directory. For now
use the link https://codeload.patternhouse.tk/json/contributors.json which
currently does not exist but I will make sure it will be one the workflow
is working.

**Comment by Daksh777** [comment]
I was proposing an idea but it seems like https://patternhouse.tk no longer works
![image](https://user-images.githubusercontent.com/43648146/148078019-e3716f51-9331-432f-a62c-2c5a59c6d2a2.png)
Is the domain revoked?

**Comment by Daksh777** [comment]
Here's my proposal:

![image](https://user-images.githubusercontent.com/43648146/148079363-e516849a-70f4-4a64-8d38-8b1e57baebed.png)

We can have a section right on the main website with the 
- profile picture
- rank/number (sorted by commit count)
- name
- the number of contributions 
as shown in the picture above.

However, I'd need some help with implementing the JSON for parsing the data.

**Comment by cyberbuddy-manas** [comment]
> Here's my proposal:
> However, I'd need some help with implementing the JSON for parsing the data.

Cool @Daksh777 had something similar in my mind. Well I'll use the same design and add HTML and CSS accordingly. Then I'll add data in the cards dynamically and will code for top 20 or whatever amount of contributors to be shown using JS. Shall I give it a try?

**Comment by Daksh777** [comment]
That sounds great. You can use the existing card grid and styles. For example, this is what I used:

``` html
                <div class="card p-4 p-md-3 col-md-6 col-lg-3">
                    <div class="card-box">
                        <img src="https://avatars.githubusercontent.com/u/73778637?v=4" style="border-radius: 22px;"><br>
                        <div class="title">
                            <span class="num display-1"><strong>02.</strong></span>
                        </div>
                        <h4 class="card-title display-5">
                            <strong>Anshuman Sharma</strong></h4>
                        <p class="text-normal card-text display-7">
                            Contributions: 128</p>
                    </div>
                </div>
```

For now, you can try putting it in the same section as the thank you section, we can later create another section if that works.

**Comment by cyberbuddy-manas** [comment]
> That sounds great. You can use the existing card grid and styles. For example, this is what I used:
> For now, you can try putting it in the same section as the thank you section, we can later create another section if that works.

@Daksh777 So we're using bootstrap

**Comment by Daksh777** [comment]
Yes. Since we already have the grid and cards ready, we can directly make use of it.

**Comment by cyberbuddy-manas** [comment]
> Yes. Since we already have the grid and cards ready, we can directly make use of it.

Which Font are you using?

**Comment by Daksh777** [comment]
I'm using Jost from Google Fonts
https://github.com/PatternHouse/Central/blob/e67a004e521de4419e294fcf0cdb8b1fe0985aa2/Sources/WebMain/index.html#L16-L22

**Comment by ChlorinePentoxide** [comment]
I am looking into the nx_domain error might be a Vercel service degradation @Daksh777

**Comment by ChlorinePentoxide** [comment]
The website is back up online. :) @Daksh777

**Comment by cyberbuddy-manas** [comment]
Awesome. Design is ready as well. Just work on that api part and we can launch contributors page.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by Daksh777** [comment]
@cyberbuddy-manas could you try testing it with the JSON file I had sent a few messages above?
I'll add a new section for contributors in the meanwhile so we can add the contributors in that section

**Comment by cyberbuddy-manas** [comment]
Yeah sure, I'll send you the picture of the cards.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ChlorinePentoxide** [comment]
@Daksh777 @cyberbuddy-manas Our new official Discord server has been created. Join the discord server here: https://discord.gg/Gg8DaSQ7 (expires in 7-days). We have a few important subjects that require the community's inputs. @aryashah2k can you forward this to as many as possible.

**Comment by aryashah2k** [comment]
Sure, will do that at the earliest

**Comment by Daksh777** [comment]
Hey @cyberbuddy-manas, any update on the issue?

**Comment by cyberbuddy-manas** [comment]
Yeah, I have successfully made up the js code for adding cards and data will be fetched from the json format. Now I need the api so that we can fetch the json data from there.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ChlorinePentoxide** [comment]
@cyberbuddy-manas Let us wait for that. Since we will have domain change after the renaming.

**Comment by cyberbuddy-manas** [comment]
Cool, I'll share the design of the cards today in the morning.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cyberbuddy-manas** [comment]
> @cyberbuddy-manas Let us wait for that. Since we will have domain change after the renaming.

Hi @Daksh777  @ChlorinePentoxide. Happy Lohri:fire: Here's the design. Just share the changes you would like to have
![image](https://user-images.githubusercontent.com/70315395/149287470-e2e6f7fc-3f09-44be-80e8-60d36856e75d.png)
![image](https://user-images.githubusercontent.com/70315395/149287387-d239e9c8-eea3-4678-ab05-23a4dca6c4bc.png)
![image](https://user-images.githubusercontent.com/70315395/149287504-a2d0611d-af1c-4204-a568-a8f4ed665421.png)

**Comment by ChlorinePentoxide** [comment]
@cyberbuddy-manas It looks good! Nice job :)

**Comment by Daksh777** [comment]
Looks amazing!
I'll create a PR to add the contributors section and do the other changes and then you can commit to the same branch and we'll combine it in a single PR. Is that okay with you @cyberbuddy-manas?

**Comment by cyberbuddy-manas** [comment]
Sure

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Daksh777** [comment]
Hey @ChlorinePentoxide, I see that you added the Powered by Vercel image in the footer but do we really need that since we're already mentioning Vercel in the thank you section?

**Comment by ChlorinePentoxide** [comment]
@Daksh777 That is required as the terms of sponsorship explicitly mention its inclusion in the footer of the webpage. Can you also reduce the size of the banner (its a SVG).

**Comment by cyberbuddy-manas** [comment]
May I reduce it?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Daksh777** [comment]
> @Daksh777 That is required as the terms of sponsorship explicitly mention its inclusion in the footer of the webpage. Can you also reduce the size of the banner (its a SVG).

Makes sense, alright.

> May I reduce it? 

It's alright, I'm already adding the logos instead of the numbering in the thank you section, so I'll do that as well.

**Comment by cyberbuddy-manas** [comment]
Cool

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Daksh777** [comment]
Hey @ChlorinePentoxide, it seems like the images are not being fetched
![image](https://user-images.githubusercontent.com/43648146/149871899-0eda22c2-80ac-444c-97a3-bf578a1edc89.png)

Looking over at the network, the images are getting a 308 status. Do you have any idea why?

**Comment by cyberbuddy-manas** [comment]
@ChlorinePentoxide Any updates on the api?
